language: php

php:
  - 5.4

before_script: 
  - composer install --dev
  - echo 'CREATE DATABASE universibo' | psql -U postgres
  - echo 'CREATE DATABASE universibo_forum3' | psql -U postgres
  - echo "CREATE USER universibo WITH PASSWORD 'universibo'" | psql -U postgres
  - echo "GRANT ALL PRIVILEGES ON DATABASE universibo TO universibo" | psql -U postgres
  - echo "GRANT ALL PRIVILEGES ON DATABASE universibo_forum3 TO universibo" | psql -U postgres
  - cat app/sql/pgsql/devdb.sql | psql -U postgres universibo
  - cat vendor/universibo/forum-bundle/Universibo/Bundle/ForumBundle/Tests/Resources/sql/{structure,data}-postgres.sql | sed 's/OWNER TO.*/OWNER TO universibo;/' | psql -U postgres universibo_forum3

script:
  - bin/phpunit -c app
  - bin/behat @UniversiboWebsiteBundle -v

notifications:
  email: dev_universibo@mama.ing.unibo.it
