fos_advanced_encoder:
  encoders:
    md5:
      id: universibo_website.encoder.md5
    sha1:
      id: universibo_website.encoder.sha1
      
security:
    encoders:
        Universibo\Bundle\CoreBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:
          - ROLE_USER
          - ROLE_MODERATOR
          - ROLE_PROFESSOR
          - ROLE_STAFF
        ROLE_PROFESSOR: [ROLE_TUTOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                default_target_path: /my/universibo
            logout:
                path:   /logout
                target: /
                handler:
                  - universibo_shibboleth.logout_handler
                  - universibo_forum.logout_handler
                  - universibo_website.privacy.logout_handler
                invalidate_session: false
            shibboleth: ~
    access_control:
      - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
      - { path: ^/my, roles: IS_AUTHENTICATED_FULLY }
      - { path: \badd\b, roles: IS_AUTHENTICATED_FULLY }
      - { path: \badmin\b, roles: IS_AUTHENTICATED_FULLY }
      - { path: \bdelete\b, roles: IS_AUTHENTICATED_FULLY }
      - { path: \bedit\b, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/dashboard, roles: ROLE_ADMIN }
      - { path: ^/gestione, roles: ROLE_MODERATOR }
      - { path: ^/docente, roles: ROLE_MODERATOR }
      - { path: ^/forumlogin, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/role, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
